### ISSUE TITLE
Add number of eligible voters

### ISSUE THREAD

**Issue by catrope** [OSVTAC/osv-sample-data#1]
Add the number of eligible voters for each election, based on per-county data from the CA SoS

**Comment by carl3** [comment]
Sample data has a new object, "turnout" in the election object with similar attributes as a contest but no choices for vote for number. The contest-status.json top has a "TURNOUT" section loaded into the election.turnout. One of the result_stats is RSEli, eligible voters.

The templates have not been modified to add a turnout section.

**Comment by catrope** [comment]
Data added in 03ed7cd513a1441e57ef606cd800bdc9b663b43c
